# BƯỚC 1: KẾT NỐI GOOGLE DRIVE VÀ KIỂM TRA MÔI TRƯỜNG
## 1.1. Kết nối Google Drive, kiểm tra Python và tạo thư mục làm việc

In [35]:

from google.colab import drive
import os
import sys

# Kết nối Google Drive
drive.mount('/content/drive')

# Kiểm tra phiên bản Python
print("Phiên bản Python hiện tại:", sys.version)

# Tạo thư mục lưu bài thực hành
workspace_dir = '/content/drive/MyDrive/CDCS_KTCNTT1_Labs'
os.makedirs(workspace_dir, exist_ok=True)

print("Đã sẵn sàng thư mục làm việc:", workspace_dir)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Phiên bản Python hiện tại: 3.13.15 (main, Aug  6 2026, 11:06:22) [GCC 13.3.0]
Đã sẵn sàng thư mục làm việc: /content/drive/MyDrive/CDCS_KTCNTT1_Labs

# BƯỚC 2: CÀI ĐẶT THƯ VIỆN VÀ CẤU HÌNH GIT
## 2.1. Kiểm tra phiên bản các thư viện Python

In [36]:

import numpy as np
import pandas as pd
import matplotlib
import seaborn as sns
import sklearn

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
print("Matplotlib:", matplotlib.__version__)
print("Seaborn:", sns.__version__)
print("Scikit-Learn:", sklearn.__version__)

NumPy: 2.1.3
Pandas: 2.2.3
Matplotlib: 3.10.0
Seaborn: 0.13.2
Scikit-Learn: 1.6.1

## 2.2. Cài đặt các thư viện bổ sung Plotly, Openpyxl và Missingno

In [37]:

!pip install --quiet plotly openpyxl missingno

print("Đã cài đặt các thư viện bổ sung!")

Đã cài đặt các thư viện bổ sung!

## 2.3. Cấu hình Git và khởi tạo Repository

In [38]:

# Cấu hình danh tính Git
!git config --global user.name "Tran Ngoc Quang Dat "
!git config --global user.email "tranngocquangdat9a9@gmail.com"

# Di chuyển đến thư mục bài thực hành
%cd /content/drive/MyDrive/CDCS_KTCNTT1_Labs

# Khởi tạo Git
!git init

print("Đã cấu hình Git thành công!")

/content/drive/MyDrive/CDCS_KTCNTT1_Labs
Reinitialized existing Git repository in /content/drive/MyDrive/CDCS_KTCNTT1_Labs/.git/
Đã cấu hình Git thành công!

## 2.4. Tạo README.md và thực hiện Git Commit

In [39]:

# Tạo file README.md
with open("README.md", "w", encoding="utf-8") as f:
    f.write("# CDCS KTCNTT 1 - LAB EXERCISES\n")
    f.write("Sinh vien: Tran Ngoc Quang Dat\n")
    f.write("MSSV: 2400004124\n")

# Lưu thay đổi vào Git
!git add README.md
!git commit -m "Init repo CDCS KTCNTT 1"

# Kiểm tra trạng thái
!git status

On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	don_hang_lon.xlsx
	iris_bai2.csv
	iris_processed.csv
	iris_processed.xlsx

nothing added to commit but untracked files present (use "git add" to track)
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	don_hang_lon.xlsx
	iris_bai2.csv
	iris_processed.csv
	iris_processed.xlsx

nothing added to commit but untracked files present (use "git add" to track)

In [68]:

# Thêm các file kết quả vào Git
!git add README.md
!git add don_hang_lon.xlsx
!git add iris_bai2.csv
!git add iris_processed.csv
!git add iris_processed.xlsx

# Kiểm tra trạng thái
!git status

On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   don_hang_lon.xlsx
	new file:   iris_bai2.csv
	new file:   iris_processed.csv
	new file:   iris_processed.xlsx

## 2.5. Thêm các tệp dữ liệu vào Git Repository

In [70]:


!git commit -m "Add Lab01 data processing results"


!git status

On branch master
nothing to commit, working tree clean
On branch master
nothing to commit, working tree clean

# BƯỚC 3: THAO TÁC NÂNG CAO VỚI MẢNG NUMPY NDARRAY
## 3.1. Khởi tạo ma trận ngẫu nhiên 5x4

In [40]:

import numpy as np

# Tạo ma trận ngẫu nhiên 5x4
np.random.seed(42)

matrix = np.random.randn(5, 4) * 10 + 50

print("Ma trận ban đầu:")
print(np.round(matrix, 2))

Ma trận ban đầu:
[[54.97 48.62 56.48 65.23]
 [47.66 47.66 65.79 57.67]
 [45.31 55.43 45.37 45.34]
 [52.42 30.87 32.75 44.38]
 [39.87 53.14 40.92 35.88]]

## 3.2. Cắt lát ma trận hai chiều (Slicing)

In [41]:

# Lấy hàng có chỉ số 1, 2, 3
# Lấy cột có chỉ số 2, 3
sub_matrix = matrix[1:4, 2:4]

print("Ma trận con:")
print(np.round(sub_matrix, 2))

Ma trận con:
[[65.79 57.67]
 [45.37 45.34]
 [32.75 44.38]]

## 3.3. Tính toán các đại lượng thống kê theo cột

In [42]:

# Tính thống kê theo từng cột
col_mean = np.mean(matrix, axis=0)
col_std = np.std(matrix, axis=0)
col_median = np.median(matrix, axis=0)

print("Trung bình từng cột:", np.round(col_mean, 2))
print("Độ lệch chuẩn từng cột:", np.round(col_std, 2))
print("Trung vị từng cột:", np.round(col_median, 2))

Trung bình từng cột: [48.04 47.14 48.26 49.7 ]
Độ lệch chuẩn từng cột: [ 5.32  8.62 11.64 10.42]
Trung vị từng cột: [47.66 48.62 45.37 45.34]

## 3.4. Broadcasting - Trừ trung bình từng cột

In [43]:

# Trừ từng phần tử cho trung bình cột tương ứng
matrix_centered = matrix - col_mean

print("Ma trận sau Broadcasting:")
print(np.round(matrix_centered, 2))

# Kiểm tra trung bình từng cột sau biến đổi
print("Trung bình sau biến đổi:")
print(np.round(np.mean(matrix_centered, axis=0), 2))

Ma trận sau Broadcasting:
[[  6.92   1.48   8.22  15.53]
 [ -0.39   0.52  17.53   7.97]
 [ -2.74   8.28  -2.9   -4.36]
 [  4.38 -16.28 -15.51  -5.32]
 [ -8.17   6.    -7.34 -13.82]]
Trung bình sau biến đổi:
[ 0. -0. -0.  0.]

# BƯỚC 4: KHỞI TẠO VÀ LÀM VIỆC VỚI PANDAS
## 4.1. Khởi tạo Pandas Series quản lý điểm số

In [44]:

import pandas as pd

# Tạo Series điểm số sinh viên
scores = pd.Series(
    [8.5, 9.0, 7.5, 8.0, 9.5],
    index=['Toan', 'Ly', 'Hoa', 'Van', 'Anh']
)

# Hiển thị toàn bộ Series
print("Danh sách điểm:")
print(scores)

# Truy xuất điểm môn Toán
print("\nĐiểm môn Toán:", scores['Toan'])

# Lọc các môn có điểm >= 8.5
print("\nCác môn có điểm >= 8.5:")
print(scores[scores >= 8.5])

Danh sách điểm:
Toan    8.5
Ly      9.0
Hoa     7.5
Van     8.0
Anh     9.5
dtype: float64

Điểm môn Toán: 8.5

Các môn có điểm >= 8.5:
Toan    8.5
Ly      9.0
Anh     9.5
dtype: float64

## 4.2. Khởi tạo DataFrame quản lý nhân viên

In [45]:

# Khởi tạo dữ liệu nhân viên
data = {
    'MaNV': ['NV01', 'NV02', 'NV03', 'NV04', 'NV05'],
    'HoTen': [
        'Nguyen Van An',
        'Tran Thi Binh',
        'Le Van Cuong',
        'Pham Thi Dung',
        'Hoang Van Em'
    ],
    'PhongBan': [
        'IT', 'Kinh Doanh', 'IT',
        'Nhan Su', 'Kinh Doanh'
    ],
    'Luong': [
        25000000, 18000000, 30000000,
        15000000, 22000000
    ],
    'ThamNien': [3, 2, 5, 1, 4]
}

# Tạo DataFrame
df_nv = pd.DataFrame(data)

print("Bảng thông tin nhân viên:")
display(df_nv)

Bảng thông tin nhân viên:

   MaNV          HoTen    PhongBan     Luong  ThamNien
0  NV01  Nguyen Van An          IT  25000000         3
1  NV02  Tran Thi Binh  Kinh Doanh  18000000         2
2  NV03   Le Van Cuong          IT  30000000         5
3  NV04  Pham Thi Dung     Nhan Su  15000000         1
4  NV05   Hoang Van Em  Kinh Doanh  22000000         4

## 4.3. Truy xuất và lọc dữ liệu bằng loc, iloc

In [46]:

# Truy xuất nhân viên thứ 3 bằng iloc
print("Nhân viên thứ 3:")
print(df_nv.iloc[2])

# Truy xuất bằng loc với nhãn index = 2
print("\nTruy xuất bằng loc:")
print(df_nv.loc[2])

# Lọc các nhân viên thuộc phòng IT
print("\nDanh sách nhân viên phòng IT:")
display(df_nv[df_nv['PhongBan'] == 'IT'])

Nhân viên thứ 3:
MaNV                NV03
HoTen       Le Van Cuong
PhongBan              IT
Luong           30000000
ThamNien               5
Name: 2, dtype: object

Truy xuất bằng loc:
MaNV                NV03
HoTen       Le Van Cuong
PhongBan              IT
Luong           30000000
ThamNien               5
Name: 2, dtype: object

Danh sách nhân viên phòng IT:

   MaNV          HoTen PhongBan     Luong  ThamNien
0  NV01  Nguyen Van An       IT  25000000         3
2  NV03   Le Van Cuong       IT  30000000         5

# BƯỚC 5: KHÁM PHÁ THUỘC TÍNH VÀ ĐỌC GHI DỮ LIỆU THỰC TẾ
## 5.1. Đọc bộ dữ liệu Iris từ GitHub

In [47]:

import pandas as pd

# Đường dẫn dữ liệu Iris từ GitHub
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

# Đọc dữ liệu CSV
df_iris = pd.read_csv(url)

# Hiển thị 5 dòng đầu tiên
print("5 dòng đầu tiên của dữ liệu Iris:")
display(df_iris.head())

5 dòng đầu tiên của dữ liệu Iris:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

## 5.2. Khám phá cấu trúc và thống kê dữ liệu Iris

In [48]:

# Kiểm tra kích thước dữ liệu
print("Kích thước bộ dữ liệu:", df_iris.shape)

# Hiển thị 5 dòng đầu tiên
print("\n5 dòng đầu tiên:")
display(df_iris.head())

# Kiểm tra thông tin các cột
print("\nThông tin kỹ thuật các cột:")
df_iris.info()

# Thống kê mô tả
print("\nThống kê mô tả:")
display(df_iris.describe())

Kích thước bộ dữ liệu: (150, 5)

5 dòng đầu tiên:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Thông tin kỹ thuật các cột:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

Thống kê mô tả:

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

## 5.3. Xuất dữ liệu Iris ra tệp CSV

In [49]:

import os

# Đường dẫn thư mục trên Google Drive
workspace_dir = '/content/drive/MyDrive/CDCS_KTCNTT1_Labs'

# Đảm bảo thư mục tồn tại
os.makedirs(workspace_dir, exist_ok=True)

# Xuất dữ liệu sang file CSV
csv_path = os.path.join(workspace_dir, 'iris_processed.csv')

df_iris.to_csv(csv_path, index=False)

print("Đã lưu tệp iris_processed.csv thành công!")
print("Đường dẫn:", csv_path)

Đã lưu tệp iris_processed.csv thành công!
Đường dẫn: /content/drive/MyDrive/CDCS_KTCNTT1_Labs/iris_processed.csv

## 5.4. Xuất dữ liệu Iris ra tệp Excel

In [50]:

# Xuất dữ liệu ra file Excel
excel_path = os.path.join(workspace_dir, 'iris_processed.xlsx')

df_iris.to_excel(excel_path, index=False)

print("Đã lưu tệp iris_processed.xlsx thành công!")

Đã lưu tệp iris_processed.xlsx thành công!

# PHẦN IV: BÀI TẬP VẬN DỤNG VÀ MỞ RỘNG
# BÀI 1: XỬ LÝ MA TRẬN NUMPY 6x6
## 1.1. Khởi tạo ma trận ngẫu nhiên 6x6

In [51]:

import numpy as np

# Cố định kết quả ngẫu nhiên
np.random.seed(42)

# Tạo ma trận 6x6 gồm số nguyên từ 10 đến 99
matrix6 = np.random.randint(10, 100, size=(6, 6))

print("Ma trận ban đầu:")
print(matrix6)

Ma trận ban đầu:
[[61 24 81 70 30 92]
 [96 84 84 97 33 12]
 [31 62 11 97 39 47]
 [11 73 69 30 42 85]
 [67 31 98 58 68 51]
 [69 89 24 71 71 56]]

## 1.2. Câu a - Thay các phần tử đường chéo chính bằng 0

In [52]:

# Thay các phần tử đường chéo chính bằng 0
np.fill_diagonal(matrix6, 0)

print("Ma trận sau khi thay đường chéo chính:")
print(matrix6)

Ma trận sau khi thay đường chéo chính:
[[ 0 24 81 70 30 92]
 [96  0 84 97 33 12]
 [31 62  0 97 39 47]
 [11 73 69  0 42 85]
 [67 31 98 58  0 51]
 [69 89 24 71 71  0]]

## 1.3. Câu b - Lọc phần tử lớn hơn 50 và tính trung bình

In [53]:

# Trích xuất các phần tử lớn hơn 50
greater_than_50 = matrix6[matrix6 > 50]

print("Các phần tử lớn hơn 50:")
print(greater_than_50)

# Tính trung bình cộng
average = np.mean(greater_than_50)

print("Trung bình cộng:", average)

Các phần tử lớn hơn 50:
[81 70 92 96 84 97 62 97 73 69 85 67 98 58 51 69 89 71 71]
Trung bình cộng: 77.89473684210526

## 1.4. Câu c - Chuẩn hóa ma trận bằng phương pháp Min-Max

In [54]:

# Tìm giá trị nhỏ nhất và lớn nhất
min_val = np.min(matrix6)
max_val = np.max(matrix6)

# Chuẩn hóa Min-Max
if max_val != min_val:
    matrix_normalized = (
        (matrix6 - min_val) / (max_val - min_val)
    )
else:
    matrix_normalized = np.zeros_like(matrix6, dtype=float)

print("Giá trị nhỏ nhất:", min_val)
print("Giá trị lớn nhất:", max_val)

print("\nMa trận sau khi chuẩn hóa:")
print(np.round(matrix_normalized, 2))

Giá trị nhỏ nhất: 0
Giá trị lớn nhất: 98

Ma trận sau khi chuẩn hóa:
[[0.   0.24 0.83 0.71 0.31 0.94]
 [0.98 0.   0.86 0.99 0.34 0.12]
 [0.32 0.63 0.   0.99 0.4  0.48]
 [0.11 0.74 0.7  0.   0.43 0.87]
 [0.68 0.32 1.   0.59 0.   0.52]
 [0.7  0.91 0.24 0.72 0.72 0.  ]]

## 1.5. Kiểm tra kết quả Bài tập 1

In [71]:

print(" KIỂM TRA BÀI 1 ")

print("Kích thước ma trận:", matrix6.shape)

print("Đường chéo chính:", np.diag(matrix6))

print("Số phần tử lớn hơn 50:", len(greater_than_50))

print("Trung bình các phần tử > 50:", round(average, 2))

print("Min sau chuẩn hóa:", matrix_normalized.min())
print("Max sau chuẩn hóa:", matrix_normalized.max())

 KIỂM TRA BÀI 1
Kích thước ma trận: (6, 6)
Đường chéo chính: [0 0 0 0 0 0]
Số phần tử lớn hơn 50: 19
Trung bình các phần tử > 50: 77.89
Min sau chuẩn hóa: 0.0
Max sau chuẩn hóa: 1.0

# BÀI 2: PHÂN TÍCH DỮ LIỆU IRIS BẰNG PANDAS
## 2.1. Kiểm tra bộ dữ liệu Iris

In [56]:

# Kiểm tra bộ dữ liệu Iris
print("Kích thước dữ liệu:", df_iris.shape)

print("\n5 dòng đầu tiên:")
display(df_iris.head())

print("\nCác loài hoa:")
print(df_iris['species'].unique())

Kích thước dữ liệu: (150, 5)

5 dòng đầu tiên:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Các loài hoa:
['setosa' 'versicolor' 'virginica']

## 2.2. Câu a - Lọc hoa Versicolor có Sepal Length lớn hơn 6.0

In [57]:

# Lọc loài versicolor và sepal_length > 6.0
df_filtered = df_iris[
    (df_iris['species'] == 'versicolor') &
    (df_iris['sepal_length'] > 6.0)
]

print("Các hoa versicolor có sepal_length > 6.0:")
display(df_filtered)

print("Số bản ghi thỏa mãn:", len(df_filtered))

Các hoa versicolor có sepal_length > 6.0:

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
54           6.5          2.8           4.6          1.5  versicolor
56           6.3          3.3           4.7          1.6  versicolor
58           6.6          2.9           4.6          1.3  versicolor
63           6.1          2.9           4.7          1.4  versicolor
65           6.7          3.1           4.4          1.4  versicolor
68           6.2          2.2           4.5          1.5  versicolor
71           6.1          2.8           4.0          1.3  versicolor
72           6.3          2.5           4.9          1.5  versicolor
73           6.1          2.8           4.7          1.2  versicolor
74           6.4          2.9           4.3          1.3  versicolor
75           6.6          3.0           4.4          1.4  versicolor
76           6.8          2.8           4.8          1.4  versicolor
77           6.7          3.0           5.0          1.7  versicolor
86           6.7          3.1           4.7          1.5  versicolor
87           6.3          2.3           4.4          1.3  versicolor
91           6.1          3.0           4.6          1.4  versicolor
97           6.2          2.9           4.3          1.3  versicolor

Số bản ghi thỏa mãn: 20

## 2.3. Câu b - Thêm cột Petal Ratio

In [58]:

# Tạo cột petal_ratio
df_iris['petal_ratio'] = (
    df_iris['petal_length'] / df_iris['petal_width']
)

print("Dữ liệu Iris sau khi thêm cột petal_ratio:")
display(df_iris.head())

print("Kích thước dữ liệu mới:", df_iris.shape)

Dữ liệu Iris sau khi thêm cột petal_ratio:

   sepal_length  sepal_width  petal_length  petal_width species  petal_ratio
0           5.1          3.5           1.4          0.2  setosa          7.0
1           4.9          3.0           1.4          0.2  setosa          7.0
2           4.7          3.2           1.3          0.2  setosa          6.5
3           4.6          3.1           1.5          0.2  setosa          7.5
4           5.0          3.6           1.4          0.2  setosa          7.0

Kích thước dữ liệu mới: (150, 6)

## 2.4. Câu c - Tính trung bình Petal Ratio theo từng loài

In [59]:

# Nhóm dữ liệu theo loài hoa và tính trung bình
mean_ratio = df_iris.groupby('species')['petal_ratio'].mean()

print("Trung bình petal_ratio theo từng loài hoa:")
print(mean_ratio.round(2))

Trung bình petal_ratio theo từng loài hoa:
species
setosa        6.91
versicolor    3.24
virginica     2.78
Name: petal_ratio, dtype: float64

## 2.5. Kiểm tra kết quả Bài tập 2

In [72]:

print(" KIỂM TRA BÀI 2 =")

print("\nCâu a - Số bản ghi thỏa mãn:")
print(len(df_filtered))

print("\nCâu b - Danh sách các cột:")
print(df_iris.columns.tolist())

print("\nCâu c - Trung bình petal_ratio:")
print(mean_ratio.round(2))

print("\nKích thước DataFrame:", df_iris.shape)

 KIỂM TRA BÀI 2 =

Câu a - Số bản ghi thỏa mãn:
20

Câu b - Danh sách các cột:
['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species', 'petal_ratio']

Câu c - Trung bình petal_ratio:
species
setosa        6.91
versicolor    3.24
virginica     2.78
Name: petal_ratio, dtype: float64

Kích thước DataFrame: (150, 6)

## 2.6. Lưu dữ liệu sau xử lý ra tệp CSV

In [61]:

import os

workspace_dir = '/content/drive/MyDrive/CDCS_KTCNTT1_Labs'

# Lưu dữ liệu Iris sau khi thêm cột
df_iris.to_csv(
    os.path.join(workspace_dir, 'iris_bai2.csv'),
    index=False
)

print("Đã lưu kết quả Bài 2 thành công!")

Đã lưu kết quả Bài 2 thành công!

# BÀI 3: QUẢN LÝ ĐƠN HÀNG BẰNG PANDAS
## 3.1. Khởi tạo DataFrame gồm 10 đơn hàng

In [62]:

import pandas as pd

# Tạo dữ liệu 10 đơn hàng
data_orders = {
    'MaDH': [
        'DH01', 'DH02', 'DH03', 'DH04', 'DH05',
        'DH06', 'DH07', 'DH08', 'DH09', 'DH10'
    ],
    'NgayDat': [
        '2026-10-01', '2026-10-02', '2026-10-03',
        '2026-10-04', '2026-10-05', '2026-10-06',
        '2026-10-07', '2026-10-08', '2026-10-09',
        '2026-10-10'
    ],
    'KhachHang': [
        'Nguyen Van An', 'Tran Thi Binh',
        'Le Van Cuong', 'Pham Thi Dung',
        'Hoang Van Em', 'Nguyen Thi Hoa',
        'Tran Van Nam', 'Le Thi Lan',
        'Pham Van Minh', 'Vo Thi Mai'
    ],
    'SoLuong': [2, 5, 1, 3, 4, 2, 6, 1, 5, 3],
    'DonGia': [
        1500000, 1200000, 4500000, 2000000,
        900000, 3500000, 800000, 6000000,
        1100000, 2500000
    ]
}

# Tạo DataFrame
df_orders = pd.DataFrame(data_orders)

# Chuyển cột ngày đặt sang kiểu datetime
df_orders['NgayDat'] = pd.to_datetime(df_orders['NgayDat'])

print("Danh sách 10 đơn hàng:")
display(df_orders)

Danh sách 10 đơn hàng:

   MaDH    NgayDat       KhachHang  SoLuong   DonGia
0  DH01 2026-10-01   Nguyen Van An        2  1500000
1  DH02 2026-10-02   Tran Thi Binh        5  1200000
2  DH03 2026-10-03    Le Van Cuong        1  4500000
3  DH04 2026-10-04   Pham Thi Dung        3  2000000
4  DH05 2026-10-05    Hoang Van Em        4   900000
5  DH06 2026-10-06  Nguyen Thi Hoa        2  3500000
6  DH07 2026-10-07    Tran Van Nam        6   800000
7  DH08 2026-10-08      Le Thi Lan        1  6000000
8  DH09 2026-10-09   Pham Van Minh        5  1100000
9  DH10 2026-10-10      Vo Thi Mai        3  2500000

## 3.2. Câu a - Tính thành tiền cho từng đơn hàng

In [63]:

# Tính thành tiền cho từng đơn hàng
df_orders['ThanhTien'] = (
    df_orders['SoLuong'] * df_orders['DonGia']
)

print("Danh sách đơn hàng sau khi tính thành tiền:")
display(df_orders)

Danh sách đơn hàng sau khi tính thành tiền:

   MaDH    NgayDat       KhachHang  SoLuong   DonGia  ThanhTien
0  DH01 2026-10-01   Nguyen Van An        2  1500000    3000000
1  DH02 2026-10-02   Tran Thi Binh        5  1200000    6000000
2  DH03 2026-10-03    Le Van Cuong        1  4500000    4500000
3  DH04 2026-10-04   Pham Thi Dung        3  2000000    6000000
4  DH05 2026-10-05    Hoang Van Em        4   900000    3600000
5  DH06 2026-10-06  Nguyen Thi Hoa        2  3500000    7000000
6  DH07 2026-10-07    Tran Van Nam        6   800000    4800000
7  DH08 2026-10-08      Le Thi Lan        1  6000000    6000000
8  DH09 2026-10-09   Pham Van Minh        5  1100000    5500000
9  DH10 2026-10-10      Vo Thi Mai        3  2500000    7500000

## 3.3. Câu b - Lọc đơn hàng có thành tiền trên 5 triệu đồng

In [64]:

# Lọc đơn hàng có thành tiền lớn hơn 5 triệu
df_orders_large = df_orders[
    df_orders['ThanhTien'] > 5000000
]

print("Các đơn hàng có thành tiền > 5.000.000 VNĐ:")
display(df_orders_large)

print("Số đơn hàng thỏa mãn:", len(df_orders_large))

Các đơn hàng có thành tiền > 5.000.000 VNĐ:

   MaDH    NgayDat       KhachHang  SoLuong   DonGia  ThanhTien
1  DH02 2026-10-02   Tran Thi Binh        5  1200000    6000000
3  DH04 2026-10-04   Pham Thi Dung        3  2000000    6000000
5  DH06 2026-10-06  Nguyen Thi Hoa        2  3500000    7000000
7  DH08 2026-10-08      Le Thi Lan        1  6000000    6000000
8  DH09 2026-10-09   Pham Van Minh        5  1100000    5500000
9  DH10 2026-10-10      Vo Thi Mai        3  2500000    7500000

Số đơn hàng thỏa mãn: 6

## 3.4. Câu c - Xuất đơn hàng ra tệp don_hang_lon.xlsx

In [65]:

import os

# Thư mục lưu trên Google Drive
workspace_dir = '/content/drive/MyDrive/CDCS_KTCNTT1_Labs'

# Đảm bảo thư mục tồn tại
os.makedirs(workspace_dir, exist_ok=True)

# Đường dẫn file Excel
excel_path = os.path.join(
    workspace_dir,
    'don_hang_lon.xlsx'
)

# Xuất dữ liệu đã lọc ra Excel
df_orders_large.to_excel(
    excel_path,
    index=False,
    engine='openpyxl'
)

print("Đã xuất file Excel thành công!")
print("Đường dẫn:", excel_path)

Đã xuất file Excel thành công!
Đường dẫn: /content/drive/MyDrive/CDCS_KTCNTT1_Labs/don_hang_lon.xlsx

## 3.5. Kiểm tra kết quả Bài tập 3

In [73]:

print(" KIỂM TRA BÀI 3 ")

# Kiểm tra số lượng đơn hàng
print("Tổng số đơn hàng:", len(df_orders))

# Kiểm tra số đơn hàng trên 5 triệu
print("Số đơn hàng > 5 triệu:", len(df_orders_large))

# Tổng doanh thu tất cả đơn hàng
print("Tổng doanh thu: {:,} VNĐ".format(
    df_orders['ThanhTien'].sum()
))

# Tổng giá trị các đơn hàng đã lọc
print("Tổng giá trị đơn hàng lớn: {:,} VNĐ".format(
    df_orders_large['ThanhTien'].sum()
))

# Kiểm tra file Excel đã tồn tại
print("File Excel tồn tại:", os.path.exists(excel_path))

 KIỂM TRA BÀI 3
Tổng số đơn hàng: 10
Số đơn hàng > 5 triệu: 6
Tổng doanh thu: 53,900,000 VNĐ
Tổng giá trị đơn hàng lớn: 38,000,000 VNĐ
File Excel tồn tại: True

# PHẦN V: KIỂM TRA VÀ HOÀN THIỆN BÀI THỰC HÀNH
## 5.1. Kiểm tra các tệp kết quả trên Google Drive

In [67]:

import os
import shutil

workspace_dir = '/content/drive/MyDrive/CDCS_KTCNTT1_Labs'

print("Các file hiện có trong thư mục:")
for filename in os.listdir(workspace_dir):
    print("-", filename)

Các file hiện có trong thư mục:
- .git
- README.md
- iris_processed.csv
- iris_processed.xlsx
- iris_bai2.csv
- don_hang_lon.xlsx